name: Build Mrb Gamepad Pro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Zipalign and Sign Premium APK (Manual Native Method)
        env:
          KEYSTORE_B64: ${{ secrets.MRB_KEYSTORE }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          # 1. Base64 text ko wapas chabi (.jks) mein convert karo
          echo "$KEYSTORE_B64" | base64 --decode > mrb_release.jks
          
          # 2. Cloud server par sabse latest Android tools dhundo
          BUILD_TOOLS_DIR=$(ls -d $ANDROID_HOME/build-tools/* | tail -1)
          ZIPALIGN="$BUILD_TOOLS_DIR/zipalign"
          APKSIGNER="$BUILD_TOOLS_DIR/apksigner"
          
          # 3. APK ko optimize (zipalign) karo
          $ZIPALIGN -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-aligned.apk
          
          # 4. Apne original keystore se app ko Sign karo
          $APKSIGNER sign --ks mrb_release.jks --ks-key-alias "$KEY_ALIAS" --ks-pass pass:"$KEYSTORE_PASSWORD" --key-pass pass:"$KEY_PASSWORD" --out app/build/outputs/apk/release/Mrb_Gamepad_Pro_Premium.apk app/build/outputs/apk/release/app-release-aligned.apk

      - name: Upload Mrb Gamepad Pro APK
        uses: actions/upload-artifact@v4
        with:
          name: Mrb_Gamepad_Pro_Premium
          path: app/build/outputs/apk/release/Mrb_Gamepad_Pro_Premium.apk
